hotel/reserva/reserva/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from reservar.views import index, AdminList, admin_create, admin_edit, \
    ClienteDetail, ClienteList, cliente_create, cliente_edit, \
    HabitacionDetail, HabitacionList, habitacion_create, habitacion_edit, \
    ReservaDetail, ReservaList, reserva_create, reserva_edit, \
    PagoDetail, PagoList, pago_create, pago_edit

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', index, name='index'),
    url(r'^nuevoadmin$', admin_create, name='admin_crear'),
    url(r'^listaradmin', AdminList.as_view(), name='admin_listar'),
    url(r'^editaradmin/(?P<pk>\d+)/$', admin_edit, name='admin_editar'),
    url(r'^nuevocliente$', cliente_create, name='cliente_crear'),
    url(r'^listarcliente', ClienteList.as_view(), name='cliente_listar'),
    url(r'^cliente/(?P<pk>\d+)$', ClienteDetail.as_view(), name='cliente_detail'),
    url(r'^editarcliente/(?P<pk>\d+)/$', cliente_edit, name='cliente_editar'),
    url(r'^nuevohabitacion$', habitacion_create, name='habitacion_crear'),
    url(r'^listarhabitacion', HabitacionList.as_view(), name='habitacion_listar'),
    url(r'^habitacion/(?P<pk>\d+)$', HabitacionDetail.as_view(), name='habitacion_detail'),
    url(r'^editarhabitacion/(?P<pk>\d+)/$', habitacion_edit, name='habitacion_editar'),
    url(r'^nuevoreserva$', reserva_create, name='reserva_crear'),
    url(r'^listarreserva', ReservaList.as_view(), name='reserva_listar'),
    url(r'^reserva/(?P<pk>\d+)$', ReservaDetail.as_view(), name='reserva_detail'),
    url(r'^editarreserva/(?P<pk>\d+)/$', reserva_edit, name='reserva_editar'),
    url(r'^nuevopago$', pago_create, name='pago_crear'),
    url(r'^listarpago', PagoList.as_view(), name='pago_listar'),
    url(r'^pago/(?P<pk>\d+)$', PagoDetail.as_view(), name='pago_detail'),
    url(r'^editarpago/(?P<pk>\d+)/$', pago_edit, name='pago_editar'),
]

hotel/reserva/reservar/models.py
from django.db import models

class Habitacion(models.Model):
	estado_choices = (
        ('O', 'Ocupada'),
        ('D', 'Desocupada'),
    )
	nombre_habitacion = models.CharField(max_length=50)
	descripcion=models.CharField(max_length=200)
	capacidad=models.IntegerField()
	precio=models.DecimalField(max_digits=5, decimal_places=2)
	estado = models.CharField(max_length=1,choices=estado_choices,default='D')
	def __str__(self):
		return self.nombre_habitacion

class Cliente(models.Model):
    dni_cliente=models.CharField(max_length=8)
    nombre_cliente = models.CharField(max_length=50)
    apellidos_cliente = models.CharField(max_length=50)
    email=models.EmailField()
    def __str__(self):
        return self.nombre_cliente +" "+self.apellidos_cliente

class Admin(models.Model):
    nombre_completo_admin = models.CharField(max_length=50)
    def __str__(self):
        return self.nombre_completo_admin

class Reserva(models.Model):
    admin= models.ForeignKey(Admin)
    cliente= models.ForeignKey(Cliente)
    habitacion= models.ForeignKey(Habitacion)
    fecha_in=models.DateField()
    fecha_out=models.DateField()
    def __str__(self):
        return 'Cliente: '+ str(self.cliente)+' / Habit '+ str(self.habitacion)+' / Ingreso: '+str(self.fecha_in)+' / Salida: '+str(self.fecha_out)

class Pago(models.Model):
    tpago_choices = (
        ('E', 'Efectivo'),
        ('T', 'Tarjeta'),
    )
    reserva= models.OneToOneField(Reserva)
    fecha_pago=models.DateTimeField(auto_now_add=True,auto_now=False)
    tpago= models.CharField(max_length=1,choices=tpago_choices)

hotel/reserva/templates/admin_list.html
<h1></h1>
{% extends "base.html" %}
<title>{% block title %} Lista Administradores {% endblock %}</title>
{% block content %}
<h1>Lista Administradores</h1><br>
<table class="table table-bordered">
    <tbody>
        {% if object_list %}
        <thead align="center">
            <tr>
                <td><strong>#</strong></td>
                <td><strong>Acción</strong></td>
                <td><strong>Nombre</strong></td>
            </tr>
        </thead>
        {% for admin in object_list %}
        <tr>
            <td>{{ admin.id }}</td>
            <td>
                <a href="{% url 'admin_editar' admin.id %}">Editar</a>
            </td>
            <td>{{ admin.nombre_completo_admin }}</td>
        </tr>
        {% endfor %}

        {% else %}
        <h1>No hay registros de administradores</h1>
        {% endif %}
    </tbody>
</table>
{% endblock%}

hotel/reserva/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    {% block extrastatic %}
    {% endblock %}
    <link  type="text/css" rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>{% block title %} {% endblock %}</title>
</head>
<body>
<div class="container">
    {% block navbar %}
        <div class="bs-docs-section clearfix">
            <div class="row">
                <div class="col-lg-12">
                    <div class="bs-component">
                        <nav class="navbar navbar-default">
                            <div class="container-fluid">
                                <div class="navbar-header">
                                    <a class="navbar-brand" href="{% url 'index' %}">Home</a>
                                </div>
                            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                                <ul class="nav navbar-nav">
                                    <li class="dropdown">
                                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Administradores <span class="caret"></span></a>
                                        <ul class="dropdown-menu" role="menu">
                                            <li><a href="{% url 'admin_crear' %}">Registrar</a></li>
                                            <li><a href="{% url 'admin_listar' %}">Listar</a></li>
                                        </ul>
                                    </li>
                                    <li class="dropdown">
                                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Clientes <span class="caret"></span></a>
                                        <ul class="dropdown-menu" role="menu">
                                            <li><a href="{% url 'cliente_crear' %}">Registrar</a></li>
                                            <li><a href="{% url 'cliente_listar' %}">Listar</a></li>
                                        </ul>
                                    </li>
                                    <li class="dropdown">
                                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Habitaciones <span class="caret"></span></a>
                                        <ul class="dropdown-menu" role="menu">
                                            <li><a href="{% url 'habitacion_crear' %}">Registrar</a></li>
                                            <li><a href="{% url 'habitacion_listar' %}">Listar</a></li>
                                        </ul>
                                    </li>
                                    <li class="dropdown">
                                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Reservas <span class="caret"></span></a>
                                        <ul class="dropdown-menu" role="menu">
                                            <li><a href="{% url 'reserva_crear' %}">Registrar</a></li>
                                            <li><a href="{% url 'reserva_listar' %}">Listar</a></li>
                                        </ul>
                                    </li>
                                    <li class="dropdown">
                                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Pagos <span class="caret"></span></a>
                                        <ul class="dropdown-menu" role="menu">
                                            <li><a href="{% url 'pago_crear' %}">Registrar</a></li>
                                            <li><a href="{% url 'pago_listar' %}">Listar</a></li>
                                        </ul>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </nav>
                </div>
            </div>
        </div>
    </div>

   {% endblock %}
   {% if messages %}
      <div class="messages">
          {% for msg in messages %}
          <div class="alert alert-{{msg.level_tag}}" role="alert" >{{msg.message}}
          <button type='button' class='close' data-dismiss='alert' aria-label='Close'>
              <span aria-hidden='true'>&times;</span>
            </button>
          </div>
          {% endfor %}
      </div>
    {% endif %}
    {% block content %}
    <h4></h4>
    {% endblock %}
    {% block footer %}
    {% endblock%}
</div>
<script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    {% block extrajs %}
    {% endblock %}
</body>
</html>

hotel/reserva/templates/cliente_detail.html
<h1></h1>
{% extends 'base.html' %}
<title>{% block title %} Detalle Cliente {% endblock %}</title>
{% block content %}
<h1>Detalle Cliente</h1>
<h2>{{ cliente.nombre_cliente }}</h2>
<p><strong>DNI:</strong> <i>{{ cliente.dni_cliente }}</i></p>
<p><strong>Nombre completo:</strong> <i>{{ cliente.nombre_cliente }} {{ cliente.apellidos_cliente }}</i></p>
<p><strong>Nombre completo:</strong> <i>{{ cliente.email }} </i></p>
<p>
    <a href="{% url 'cliente_listar' %}"><button>Regresar</button></a>
</p>
{% endblock%}

hotel/reserva/templates/cliente_list.html
<h1></h1>
{% extends "base.html" %}
<title>{% block title %} Lista Clientes {% endblock %}</title>
{% block content %}
<h1>Lista Clientes</h1><br>

<table class="table table-bordered">
    <tbody>
        {% if object_list %}
        <thead align="center">
            <tr>
                <td><strong>#</strong></td>
                <td><strong>Acción</strong></td>
                <td><strong>DNI</strong></td>
                <td><strong>Nombres</strong></td>
            </tr>
        </thead>
        {% for cliente in object_list %}
        <tr>
            <td>{{ cliente.id }}</td>
            <td>
                <a href="{% url 'cliente_detail' cliente.id %}">Ver detalles</a> | <a href="{% url 'cliente_editar' cliente.id %}">Editar</a>
            </td>
            <td>{{ cliente.dni_cliente }}</td>
            <td>{{ cliente.nombre_cliente }}</td>
        </tr>
        {% endfor %}

        {% else %}
        <h1>No hay registros de clientes</h1>
        {% endif %}
    </tbody>
</table>
{% endblock%}

hotel/reserva/templates/create.html
<h1></h1>
{% extends "base.html" %}
<title>{% block title %} {{titulo}} {% endblock %}</title>
{% block content %}
<h1>{{titulo}}</h1>
<br>
{% if form %}
<form method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" name="" value="Salvar">
</form>
{% endif %}

{% endblock %}

hotel/reserva/templates/habitacion_detail.html
<h1></h1>
{% extends 'base.html' %}
<title>{% block title %} Detalle Habitación {% endblock %}</title>
{% block content %}
<h1>Detalle Habitación</h1>
<h2>{{ habitacion.nombre_habitacion }}</h2>
<p><strong>Descripción:</strong> <i>{{ habitacion.descripcion }}</i></p>
<p><strong>Capacidad:</strong> <i>{{ habitacion.capacidad }}</i></p>
<p><strong>Precio:</strong> <i>{{ habitacion.precio }} soles</i></p>
<p><strong>Estado:</strong> <i>{{ habitacion.get_estado_display }}</i></p>
<p>
    <a href="{% url 'habitacion_listar' %}"><button>Regresar</button></a>
</p>
{% endblock%}

hotel/reserva/templates/habitacion_list.html
<h1></h1>
{% extends "base.html" %}
<title>{% block title %} Lista Habitaciones {% endblock %}</title>
{% block content %}
<h1>Lista Habitaciones</h1><br>

<table class="table table-bordered">
    <tbody>
        {% if object_list %}
        <thead align="center">
            <tr>
                <td><strong>#</strong></td>
                <td><strong>Acción</strong></td>
                <td><strong>Nombre</strong></td>
                <td><strong>Capacidad</strong></td>
                <td><strong>Estado</strong></td>
            </tr>
        </thead>
        {% for habitacion in object_list %}
        <tr>
            <td>{{ habitacion.id }}</td>
            <td>
                <a href="{% url 'habitacion_detail' habitacion.id %}">Ver detalles</a> | <a href="{% url 'habitacion_editar' habitacion.id %}">Editar</a>
            </td>
            <td>{{ habitacion.nombre_habitacion }}</td>
            <td>{{ habitacion.capacidad }} persona(s)</td>
            <td>{{ habitacion.get_estado_display }}</td>
        </tr>
        {% endfor %}

        {% else %}
        <h1>No hay registros de habitaciones</h1>
        {% endif %}
    </tbody>
</table>
{% endblock%}

hotel/reserva/templates/index.html
<h1></h1>
{% extends "base.html" %}
<title>{% block title %} Hotel {% endblock %}</title>
{% block content %}
<p>Contenido de la aplicación</p>
{% endblock %}

hotel/reserva/templates/pago_detail.html
<h1></h1>
{% extends 'base.html' %}
<title>{% block title %} Detalle Pago {% endblock %}</title>
{% block content %}
<h1>Detalle Pago</h1><br>
<p><strong>DNI del Cliente:</strong> <i>{{ pago.reserva.cliente.dni_cliente }}</i></p>
<p><strong>Nombre completo del Cliente:</strong> <i>{{ pago.reserva.cliente }}</i></p>
<p><strong>Habitación reservada:</strong> <i>{{ pago.reserva.habitacion }}</i></p>
<p><strong>Fechas reservadas:</strong> <i>
<ul>
    <li>Ingreso: {{ pago.reserva.fecha_in }}</li>
    <li>Salida: {{ pago.reserva.fecha_out }}</li>
</ul>
</i></p>
<p><strong>Tipo de pago:</strong> <i>{{ pago.get_tpago_display }}</i></p>
<p><strong>Fecha y hora de pago:</strong> <i>{{ pago.fecha_pago }}</i></p>
<p>
    <a href="{% url 'pago_listar' %}"><button>Regresar</button></a>
</p>
{% endblock%}

hotel/reserva/templates/pago_list.html
<h1></h1>
{% extends "base.html" %}
<title>{% block title %} Lista Pagos {% endblock %}</title>
{% block content %}
<h1>Lista Pagos</h1><br>

<table class="table table-bordered">
    <tbody>
        {% if object_list %}
    <thead align="center">
        <tr>
            <td><strong>#</strong></td>
            <td><strong>Acción</strong></td>
            <td><strong>Cliente</strong></td>
            <td><strong>Habitación</strong></td>
            <td><strong>Tipo de pago</strong></td>
        </tr>
    </thead>
        {% for pago in object_list %}
        <tr>
            <td>{{ pago.id }}</td>
            <td>
                <a href="{% url 'pago_detail' pago.id %}">Ver detalles</a> | <a href="{% url 'pago_editar' pago.id %}">Editar</a>
            </td>
            <td>{{ pago.reserva.cliente }}</td>
            <td>{{ pago.reserva.habitacion }}</td>
            <td>{{ pago.get_tpago_display }} </td>
        </tr>
        {% endfor %}

        {% else %}
        <h1>No hay registros de pagos</h1>
        {% endif %}
    </tbody>
</table>
{% endblock%}

hotel/reserva/templates/reserva_detail.html
<h1></h1>
{% extends 'base.html' %}
<title>{% block title %} Detalle Reserva {% endblock %}</title>
{% block content %}
<h1>Detalle Reserva</h1><br>
<p><strong>Administrador:</strong> <i>{{ reserva.admin }}</i></p>
<p><strong>DNI del Cliente:</strong> <i>{{ reserva.cliente.dni_cliente }}</i></p>
<p><strong>Nombre completo del Cliente:</strong> <i>{{ reserva.cliente }}</i></p>
<p><strong>Habitación:</strong> <i>{{ reserva.habitacion }}</i></p>
<p><strong>Fecha de ingreso:</strong> <i>{{ reserva.fecha_in }} </i></p>
<p><strong>Fecha de salida:</strong> <i>{{ reserva.fecha_out }}</i></p>
<p>
    <a href="{% url 'reserva_listar' %}"><button>Regresar</button></a>
</p>
{% endblock%}

hotel/reserva/templates/reserva_list.html
<h1></h1>
{% extends "base.html" %}
<title>{% block title %} Lista Reservas {% endblock %}</title>
{% block content %}
<h1>Lista Reservas</h1><br>

<table class="table table-bordered">
    <tbody>
        {% if object_list %}
        <thead align="center">
            <tr>
                <td><strong>#</strong></td>
                <td><strong>Acción</strong></td>
                <td><strong>Administrador</strong></td>
                <td><strong>Cliente</strong></td>
                <td><strong>Habitación</strong></td>
            </tr>
        </thead>
        {% for reserva in object_list %}
        <tr>
            <td>{{ reserva.id }}</td>
            <td>
                <a href="{% url 'reserva_detail' reserva.id %}">Ver detalles</a> | <a href="{% url 'reserva_editar' reserva.id %}">Editar</a>
            </td>
            <td>{{ reserva.admin }}</td>
            <td>{{ reserva.cliente }} </td>
            <td>{{ reserva.habitacion }}</td>
        </tr>
        {% endfor %}

        {% else %}
        <h1>No hay registros de reservas</h1>
        {% endif %}
    </tbody>
</table>
{% endblock%}